[package]
name = "wie_util"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true }
encoding_rs = { version = "^0.8", default-features = false }
tracing = { workspace = true }
