on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

name: Rust CI

jobs:
  rust_ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [stable, beta]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-${{ matrix.rust }}-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.rust }}-build-target-

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Install required packages (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install libasound2-dev

      - name: Install required packages (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install ninja

      - name: Install cargo-msi (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo install cargo-msi

      - run: cargo fmt --all -- --check
      - run: cargo clippy --all -- -D warnings
      - run: cargo clippy --target wasm32-unknown-unknown -- -D warnings

      - name: Run tests (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $env:RUST_MIN_STACK=4194304
          cargo test --all

      - name: Run tests (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
          export RUST_MIN_STACK=4194304
          cargo test --all

      # ✅ 构建 Windows 安装包
      - name: Build MSI installer (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo msi --output target/windows-installer.msi

      # ✅ 上传安装包为 artifact
      - name: Upload MSI installer
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer-${{ matrix.rust }}
          path: target/windows-installer.msi
